name: release

on:
  push:
    tags:
      - "[0-9].[0-9]+.[0-9]+"

env:
  IMAGE: zappi/resque-exporter

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Version ${{ github.ref_name }}
          draft: false
          prerelease: false

  release-binaries:
    runs-on: ubuntu-latest
    needs: github-release
    strategy:
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Go Binaries
        uses: wangyoucao577/go-release-action@v1.52
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -X "main.tagVersion=${{ github.ref_name }}"
          extra_files: LICENSE README.md
          md5sum: true
          sha256sum: true
          asset_name: resque-exporter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}

  docker-hub-release:
    runs-on: ubuntu-latest
    needs: release-binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          build-args:
            RESQUE_EXPORTER_VERSION=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          annotations: ${{ steps.metadata.outputs.annotations }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
      - name: Update Description On Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.IMAGE }}
