name: tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Run Tests
        run: go test -json ./... > test-results.json
      - name: Annotate Tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test-results.json
